import type { Metadata } from "next";
import ContactHeader from "./ContactHeader";

export const dynamic = "force-static";

export const metadata:Metadata={title:"Contact Otverse",description:"Join the OTVERSE waitlist or contact the team."};
const roles=["Medical Student","Surgical Trainee","Surgeon","Educator","University / Institution","Hospital / Training Center","Investor / Partner","Other"];
function Form({contact=false}:{contact?:boolean}){return <form className="formGrid"><label>Full Name<input name="Name" placeholder="Eg. Jane Smith" required/></label><label>Email<input name="Email" type="email" placeholder="jane@email.com" required/></label><label>{contact?"Profession/Role ?":"Profession ?"}<select name="Profession / Role" defaultValue=""><option value="" disabled>Select one</option>{roles.map(x=><option key={x}>{x}</option>)}</select></label>{!contact&&<label>Organization / University<input name="Organization / University" placeholder="Eg. University of Glasgow"/></label>}{!contact&&<label>What are you interested in ?<select defaultValue=""><option value="" disabled>Select one</option>{["Early access","Product demo","Institutional pilot","Education partnership","Updates only"].map(x=><option key={x}>{x}</option>)}</select></label>}<label>{contact?"Message":"Message / Notes"}<textarea placeholder={contact?"Tell us how we can help.":"Tell us anything useful — your goals, training needs, or questions."}/></label><button className="button primary" type="submit">Send a message</button></form>}
export default function Contact(){return <main className="pageGradient"><span className="formTarget" id="waitlist"/><span className="formTarget" id="contact-us"/><ContactHeader/><section className="pageHero shell"><p className="sectionTag">GET IN TOUCH</p><h1>Train better. Start sooner.</h1><p>Join the early access list or speak to our team about demos, pilots, partnerships, and surgical education.</p></section><section className="formSections shell"><article className="formCard" id="waitlist-form"><p className="sectionTag">WAITLIST</p><h2>Get early access to Otverse</h2><p>Be among the first to try immersive surgical training on Meta Quest. Join the waitlist for early access, pilots, and product updates.</p><Form/></article><article className="formCard" id="contact-form"><p className="sectionTag">CONTACT US</p><h2>Let’s talk about surgical training</h2><p>Have a question, partnership idea, demo request, or institutional inquiry? Send us a message and we’ll get back to you soon.</p><Form contact/></article></section></main>}
