"use client";
import { useEffect, useState } from "react";

const steps = [["Put on your headset","Grab any Meta Quest headset. No additional hardware, no lab booking, no waiting list."],["Enter the operating theatre","Launch OTVERSE and step into a fully immersive virtual OR. Instruments are ready. Patient is prepped."],["Follow the guided stitches","Visual prompts show you exactly where to place each stitch. Learn the fundamentals before going freehand."],["Get your score","Receive instant feedback on your technique. Track improvement across sessions. Build confidence before the real OR."]];
const features = [["Immersive VR Simulation","Step into a realistic operating theatre environment built in Unity. Handle instruments, interact with tissue, and build muscle memory in a space that feels real."],["Guided Skill Learning","Follow visual stitch paths and clear prompts designed to make difficult surgical movements understandable and repeatable."],["Real-time Feedback","See how every attempt scores, identify where your technique can improve, and build confidence before entering the real OR."],["Affordable & Accessible","Train whenever you want with a standalone Meta Quest headset—without simulator labs, waiting lists, or enterprise hardware."]];
const skills = ["SUTURING","KNOT TYING","TISSUE HANDLING","NEEDLE CONTROL","WOUND CLOSURE","INSTRUMENT CONTROL","GUIDED PRACTICE","VR SIMULATION","REAL-TIME FEEDBACK","SURGICAL CONFIDENCE"];
const traction = ["Working Unity prototype with surgical instruments","Guided stitch system with real-time scoring","Companies House registered (OTVERSE.AI Ltd.)","Accepted into Techscaler Catalyst 2026 cohort","Demo Day presentation delivered","26-company competitive landscape analysis completed","Partnership interest from African medical training institutions","Clinical advisor onboarded"];

function Header(){const [scrolled,setScrolled]=useState(false);const [activeSection,setActiveSection]=useState("");useEffect(()=>{const sectionIds=["problem-section","solution-section","how-it-works-section"];const update=()=>{setScrolled(window.scrollY>16);const focusLine=window.innerHeight*.42;const active=sectionIds.find(id=>{const section=document.getElementById(id);if(!section)return false;const rect=section.getBoundingClientRect();return rect.top<=focusLine&&rect.bottom>focusLine});setActiveSection(active||"")};update();window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{window.removeEventListener("scroll",update);window.removeEventListener("resize",update)}},[]);const sectionLink=(id:string,label:string)=><a href={`#${id}`} className={activeSection===id?"active":""} aria-current={activeSection===id?"location":undefined}>{label}</a>;return <div className={`navStage ${scrolled?"isScrolled":""}`}><header className="nav"><a className="brand" href="#" aria-label="OTVERSE home"><img className="brandLogo" src="/otverse-logo.svg" alt=""/></a><nav aria-label="Main navigation">{sectionLink("problem-section","Problem")}{sectionLink("solution-section","Solution")}{sectionLink("how-it-works-section","How It Works")}<a href="/contact-us#contact-us">Contact Us</a></nav><a className="navCta" href="/contact-us#waitlist">Get Early Access</a></header></div>}
function SectionHead({tag,title,copy}:{tag:string,title:string,copy?:string}){return <div className="sectionHead"><p className="sectionTag">{tag}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function AnimatedStats(){const [values,setValues]=useState([0,0,10]);useEffect(()=>{let animation=0;let startedAt=0;const finish=[1100,26,0];if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setValues(finish);return}const tick=(time:number)=>{if(!startedAt)startedAt=time;const progress=Math.min((time-startedAt)/2750,1);const eased=1-Math.pow(1-progress,3);setValues([Math.round(finish[0]*eased),Math.round(finish[1]*eased),Math.round(10*(1-eased))]);if(progress<1)animation=window.requestAnimationFrame(tick)};const start=window.setTimeout(()=>{animation=window.requestAnimationFrame(tick)},720);return()=>{window.clearTimeout(start);window.cancelAnimationFrame(animation)}},[]);const market=values[0]>=1000?`$${(values[0]/1000).toFixed(1)}B`:`$${values[0].toLocaleString()}M`;return <section className="stats"><div><strong>{market}</strong><span>Market Opportunity</span></div><div><strong>{values[1]}</strong><span>Competitors Analysed</span></div><div><strong>{values[2]}</strong><span>Serve Students</span></div></section>}

export default function Home(){const [feature,setFeature]=useState(0);useEffect(()=>{const id=setInterval(()=>setFeature(x=>{if(x>=features.length-1){clearInterval(id);return x}const next=x+1;if(next===features.length-1)clearInterval(id);return next}),5000);return()=>clearInterval(id)},[]);return <main>
<section className="hero"><Header/><div className="heroContent shell"><p className="eyebrow">BUILDING IN GLASGOW · TECHSCALER CATALYST 2026</p><h1>The Duolingo of<br/>Surgical Skills</h1><p className="lede">Affordable VR surgical training for medical students. Practice suturing on Meta Quest — from just £15/month.</p><div className="actions"><a className="button primary" href="/contact-us#waitlist">Get Early Access</a><a className="button ghost" href="#how-it-works-section">See How It Works</a></div></div></section>
<AnimatedStats/>
<section className="light section shell problemSection" id="problem-section"><SectionHead tag="THE PROBLEM" title="Medical students are locked out of surgical practice" copy="Surgical training hasn't kept up with how students learn. Time in the operating theatre is shrinking, simulators cost a fortune, and students are left watching instead of doing."/><div className="problemGrid"><div className="problemCards"><article><b>30%</b><p>of surgical training time is lost to passive observation</p></article><article><b>£50K+</b><p>is the starting cost of existing surgical simulators</p></article><article><b>Zero</b><p>affordable, hands-on training tools exist for individual students</p></article></div></div><blockquote>“There is growing evidence that simulation-based training improves clinical performance and patient safety.”<cite>— World Health Organisation</cite></blockquote></section>
<section className="light section shell" id="solution-section"><SectionHead tag="THE SOLUTION" title="Practice surgery anytime, anywhere" copy="OTVERSE puts a virtual operating theatre in your hands. Pick up a Meta Quest headset, launch the app, and start practising real surgical techniques — guided, scored, and affordable."/><div className="featureCard"><div className="orb"/><h3>{features[feature][0]}</h3><p>{features[feature][1]}</p><div className="carousel"><button onClick={()=>setFeature(Math.max(feature-1,0))} disabled={feature===0} aria-label="Previous feature">‹</button>{features.map((_,i)=><button key={i} onClick={()=>setFeature(i)} className={i===feature?"active":""} aria-label={`Feature ${i+1}`}/>)}<button onClick={()=>setFeature(Math.min(feature+1,features.length-1))} disabled={feature===features.length-1} aria-label="Next feature">›</button></div></div></section>
<section className="light section shell" id="how-it-works-section"><SectionHead tag="HOW IT WORKS" title="Four steps to better surgical skills"/><div className="steps">{steps.map((s,i)=><article key={s[0]}><div className="stepNo">{i+1}</div><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div></section>
<section className="dark section marketSection"><div className="shell"><SectionHead tag="MARKET OPPORTUNITY" title="A $1.1B opportunity no one is serving"/><div className="market"><article><small>TAM</small><b>$1.1B</b><span>Total addressable market</span></article><article><small>SAM</small><b>$220M</b><span>Student & institutional segment</span></article><article><small>SOM</small><b>$5–10M</b><span>Achievable in 3–5 years</span></article></div><div className="marketFacts"><div><b>40,000</b><span>UK medical students</span></div><div><b>80,000+</b><span>Indian medical graduates/yr</span></div><div><b>24.8%</b><span>CAGR</span></div><div><b>$28B</b><span>Projected market by 2035</span></div></div><p className="marketNote">Students already pay £5–50/month for Pastest, Complete Anatomy, and Geeky Medics — all knowledge-based. None are hands-on. OTVERSE fills that gap.</p></div></section>
<section className="light section shell"><SectionHead tag="COMPETITION" title="26 competitors analysed. Zero serve students." copy="Think of surgical simulation like Formula 1. Today's simulators are the F1 cars — extraordinary machines that cost millions and are reserved for elite teams. OTVERSE is the racing game that lets anyone experience the thrill, learn the lines, and build real skills — without needing a pit crew or a seven-figure budget."/><div className="comparisonGrid"><div className="compare enterprise"><h3>Enterprise simulators</h3>{[["Osso VR","£100K+ · Hospital procurement · Institutional only"],["FundamentalVR","£50K+ · Haptic hardware required · Enterprise sales"],["VirtaMed","£200K+ · Physical simulator stations · University labs"],["PrecisionOS","£75K+ · Orthopaedic focus · Hospital-only deployment"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}<p>All require institutional procurement. None target individual students.</p></div><div className="compare ours"><h3>OTVERSE</h3>{["Student-affordable — from £15/month","Direct to consumer — no procurement needed","Designed for learners — guided, progressive, forgiving","Standalone headset — just a Meta Quest, no extra hardware","No procurement needed — download and start today"].map(x=><p key={x}>✓ <span>{x}</span></p>)}</div></div></section>
<section className="marquee section" aria-label="Surgical skills"><div className="shell"><div className="marqueeHead"><h2>Practice. Repeat. Improve.</h2></div></div><div className="marqueeTrack"><div className="marqueeContent">{[...skills,...skills].map((skill,i)=><span className="marqueeItem" key={`${skill}-${i}`}>{skill}<i aria-hidden="true">·</i></span>)}</div></div></section>
<section className="light section shell"><SectionHead tag="BUSINESS MODEL" title="Two revenue streams"/><div className="revenue"><article><h3>Student subscriptions</h3><b>£15–50/month</b>{["Freemium model — first module free, subscribe to unlock all","Quest Store distribution — zero acquisition friction","Individual student accounts with progress tracking"].map(x=><p key={x}>{x}</p>)}</article><article><h3>Institutional licences</h3><b>£1–5K/year</b>{["Bulk seat licences for medical schools and hospitals","Analytics dashboard — track cohort performance","Managed deployment — pre-configured headsets for labs","Custom module requests — align with curriculum needs"].map(x=><p key={x}>{x}</p>)}</article></div></section>
<section className="traction section"><div className="shell"><SectionHead tag="TRACTION" title="Building fast with validation at every step" copy="From a working Unity prototype to clinical and institutional interest, every milestone is shaped by real-world feedback and focused validation."/><div className="tractionShowcase"><div className="tractionPager" aria-label="Traction milestones"><div className="tractionItems">{traction.map(item=><div className="tractionItem" key={item}>{item}</div>)}</div></div></div></div></section>
<section className="waitlist"><p>Be the first to try OTVERSE</p><h2>JOIN THE WAITLIST. <span>NO SPAM — JUST LAUNCH UPDATES.</span></h2><a className="button sand" href="/contact-us#waitlist">Join the waitlist</a><small>We’ll notify you when early access opens. No spam, ever.</small></section>
<footer><div className="shell footerStack"><nav className="footerLinks" aria-label="Footer navigation"><a href="https://www.linkedin.com/company/otverse-ai/posts/?feedView=all" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms-of-use">Terms of Use</a></nav><p className="footerContact">© 2026 OTVERSE.AI Ltd. · Glasgow, UK · <a href="mailto:harshil@otverse.ai">harshil@otverse.ai</a> · <a href="mailto:umer@otverse.ai">umer@otverse.ai</a></p></div></footer>
</main>}
